apiVersion: v1
kind: Service
metadata:
  name: microservice-etcd
spec:
  type: ClusterIP
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: microservice-etcd