apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ms-etcd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-etcd
    spec:
      containers:
      - image: rsobook/ms-etcd:2.0.0
        name: ms-etcd
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP